### ISSUE TITLE
Task 1 -- Create GitHub account and fork two repositories

### ISSUE THREAD

**Issue by dudung** [dudung/fi4002-01-2022-2#1]
+ To access [GitHub](https://github.com) please [create account](https://github.com/signup) or [login](https://github.com/login).
+ To participate [py-jupyter-nb](https://github.com/dudung/py-jupyter-nb) repository please [fork](https://github.com/dudung/py-jupyter-nb/fork).
+ To participate [fi4002-01-2022-2](https://github.com/dudung/fi4002-01-2022-2) repository plese [fork](https://github.com/dudung/fi4002-01-2022-2/fork).

Report  your GitHub user link by repying to this message, e.g
> https://github.com/dudung

This assignment is valid until 24 Jan 2023, 11.00 GMT+07.

**Comment by mrzqi** [comment]
https://github.com/mrzqi/

**Comment by ariawahyuw** [comment]
https://github.com/ariawahyuw

**Comment by RahmaliaNur** [comment]
https://github.com/RahmaliaNur

**Comment by 4damrr** [comment]
https://github.com/4damrr

**Comment by AriaRachmat** [comment]
https://github.com/AriaRachmat

**Comment by Luqmanalifio** [comment]
https://github.com/Luqmanalifio

**Comment by ldwgvnbthvn** [comment]
https://github.com/ldwgvnbthvn

**Comment by rais1608** [comment]
https://github.com/rais1608

**Comment by axelfarrelh** [comment]
https://github.com/axelfarrelh

**Comment by RizkaFinesya** [comment]
github.com/RizkaFinesya

**Comment by thebellaproject** [comment]
https://github.com/thebellaproject

**Comment by Farrelfasya** [comment]
https://github.com/Farrelfasya

**Comment by mhaidarzz** [comment]
https://github.com/mhaidarzz

**Comment by dhsalsabila** [comment]
https://github.com/dhsalsabila

**Comment by Mfthlfrd** [comment]
https://github.com/Mfthlfrd

**Comment by ahmadmarzukiramadhan** [comment]
https://github.com/ahmadmarzukiramadhan

**Comment by 10219082Rahmalia** [comment]
https://github.com/10219082Rahmalia

**Comment by chromaaxion** [comment]
https://github.com/chromaaxion

**Comment by Blitzmaestro** [comment]
https://github.com/Blitzmaestro

**Comment by stefanyimanuel** [comment]
https://github.com/stefanyimanuel

**Comment by valensiusnathanael** [comment]
https://github.com/valensiusnathanael
