### ISSUE TITLE
Exam 1 -- Midterm Test

### ISSUE THREAD

**Issue by dudung** [dudung/fi4002-01-2022-2#4]
+ Do part a in the class on Thursday `09-mar-2023`, write it on the given answer sheet.
[fi4002-u1.pdf](https://github.com/dudung/fi4002-01-2022-2/files/10917100/fi4002-u1.pdf)
+ Do part b at home until midnight, and discuss the time extension with the class if necessary.
[Note 08](https://github.com/dudung/fi4002-01-2022-2/tree/main/note/08)
+ Make a repository using your GitHub account, namely, `midterm-answer` and post link to it here and also in [Edunex](https://edunex.itb.ac.id/courses/44705/preview/160006/68758).

**Comment by AriaRachmat** [comment]
https://github.com/AriaRachmat/midterm-answer

**Comment by valensiusnathanael** [comment]
https://github.com/valensiusnathanael/10219094_UTS_FI4002/

**Comment by valensiusnathanael** [comment]
Selamat malam Pa, perkenalkan nama saya Valensius Nathanael Huangtama, NIM 10219093, saya kesulitan mengakses edunex dari 9 Maret 2023, pukul 23.00. Sehingga saya tidak dapat mengumpulkan link tepat waktu di edunex, namun saya ingin menginfokan bahwa saya telah mengumpulkan link repositori saya di GitHub melalui comment pada 9 Maret 2023 pukul 21.27 

> https://github.com/valensiusnathanael/10219094_UTS_FI4002/

**Comment by Blitzmaestro** [comment]
https://github.com/Blitzmaestro/midterm-answer

**Comment by Luqmanalifio** [comment]
https://github.com/Luqmanalifio/fi4002-01-2022-2/tree/main/task/10219061_SPSF_UTS

**Comment by ariawahyuw** [comment]
https://github.com/ariawahyuw/midterm-exam/

**Comment by RizkaFinesya** [comment]
https://github.com/RizkaFinesya/midterm-answer

**Comment by chromaaxion** [comment]
https://github.com/chromaaxion/midterm-answer

**Comment by dhsalsabila** [comment]
https://github.com/dhsalsabila/midterm-answer

**Comment by dhsalsabila** [comment]
<img width="1053" alt="Screenshot 2023-03-18 at 13 40 10" src="https://user-images.githubusercontent.com/123042928/226089857-7b6b9d2e-2739-41f7-a908-3f61bdd6b073.png">
Selamat siang Pak, Dhia permata 10219003, izin melampirkan bukti pengumpulan uts kemarin. Terima kasih.
