### ISSUE TITLE
Perbaikan data kehadiran

### ISSUE THREAD

**Issue by dudung** [dudung/fi4002-01-2022-2#5]
+ Rekan-rekan yang ingin memperbarui data kehadiran dapat disampaikan di issue ini.
+ Tuliskan, nama, NIM, tanggal, jam, dan ruangannya, e.g. Newton Iman, 10209007, Senin, 0700-0900, 1201.
+ Terima kasih.

**Comment by raihanmr1211** [comment]
Raihan Mohammad Rahman, 20222003, Rabu 1&8 Februari, 09.00-11.00, 9310

**Comment by lattov** [comment]
Alwali Walyatalattov Solichin, 20221305, Rabu 0900-1100, 9310

Saya belum absensi karena PRS, Pak. Setelah PRS saya hanya izin ketika tanggal 21 Februari 2023, ketika sudah kelas Pak Freddy Haryanto. Terima kasih, Pak.

**Comment by NurAnnisa-NA23** [comment]
Nur Annisa, 20222014, Rabu: 25/1,1/2, 8/2, 15/2, pukul 09.00-11.00, 9310 Pak. Saya belum mengisi kehadiran karena baru memilih matkul ini saat PRS Pak. Terima kasih Pak.
