### ISSUE TITLE
Kehadiran Kamis 27 April 2023 1100-1300 (daring)

### ISSUE THREAD

**Issue by dudung** [dudung/fi4002-01-2022-2#8]
+ Silakan untuk mengisi kehadiran dengan menuliskan NIM Anda.
+ Terima kasih.

**Comment by axelfarrelh** [comment]
10219081-Axel Farrel Hutagalung

**Comment by AriaRachmat** [comment]
10219049

**Comment by dhsalsabila** [comment]
10219003 - Dhia Permata Salsabila

**Comment by ariawahyuw** [comment]
10219083 - Aria Wahyu Wicaksono

**Comment by YodaTaruna** [comment]
10219031 - Yoda Taruna Hidayah

**Comment by ldwgvnbthvn** [comment]
10217062

**Comment by mrzqi** [comment]
10218043

**Comment by RizkaFinesya** [comment]
10219047

**Comment by Farrelfasya** [comment]
10219097 - Muhammad Farrel

**Comment by chromaaxion** [comment]
10219074

**Comment by dudung** [comment]
Terima kasih, @axelfarrelh, @AriaRachmat, @dhsalsabila, @ariawahyuw, @YodaTaruna, @ldwgvnbthvn, @mrzqi, @RizkaFinesya, @Farrelfasya, @chromaaxion.

**Comment by rais1608** [comment]
10219053
